[Fixes]
ActorIsHostileToActor = true		# Fixes a crash when invoking Actor.IsHostileToActor with a none form
CellInit = true	              	# Fixes a crash where a form does not get converted to a form pointer on unloaded cells
EncounterZoneReset = true	    	# Fixes encounter zones resetting immediately once you leave them on foot
FaderMenu = true	            	# Fixes a bug where the fader menu may not fully close
SafeExit = true	              	# Fixes crashes related to exiting the game that can be caused erroneously by F4SE plugin hooks

[Patches]
MemoryManager = true	        	# Replaces the global memory manager with os allocators
ScaleformAllocator = true	    	# Replaces the scaleform memory allocator with os allocators
SmallBlockAllocator = true	  	# Replaces the small block memory allocators with os allocators
