#ifndef BFOT_VERSION_INCLUDED
#define BFOT_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define BFOT_VERSION_MAJOR 1
#define BFOT_VERSION_MINOR 1
#define BFOT_VERSION_PATCH 0
#define BFOT_VERSION_BETA 0
#define BFOT_VERSION_VERSTRING   \
	MAKE_STR(BFOT_VERSION_MAJOR) \
	"." MAKE_STR(BFOT_VERSION_MINOR) "." MAKE_STR(BFOT_VERSION_PATCH) "." MAKE_STR(BFOT_VERSION_BETA)

#endif
